version: "3"
services:
  discovery-server-1:
    build: .
    ports:
      - "8761:8761"
    networks:
        - webnet
    environment:
        - PORT=8761
        - PEER_PORT=8762
        - PEER1=discovery-server-1
        - PEER2=discovery-server-2
        - PEER3=discovery-server-3
        - APPNAME=discovery-server-1
        - NAME=discovery_server
        - CONFIG_SERVER=config_server
  discovery-server-2:
    build: .
    networks:
        - webnet
    ports:
      - "8762:8762"
    environment:
        - PORT=8762
        - PEER_PORT=8761
        - PEER1=discovery-server-1
        - PEER2=discovery-server-2
        - PEER3=discovery-server-3
        - NAME=discovery_server
        - APPNAME=discovery-server-2
  discovery-server-3:
    build: .
    networks:
        - webnet
    ports:
      - "8763:8763"
    environment:
        - PORT=8763
        - PEER_PORT=8761
        - PEER1=discovery-server-1
        - PEER2=discovery-server-2
        - PEER3=discovery-server-3
        - NAME=discovery_server
        - APPNAME=discovery-server-3

volumes:
  esdata1:
    driver: local

networks:
  webnet:
